### ISSUE TITLE
Investigate failing build on Travis due to deployment of documentation

### ISSUE THREAD

**Issue by derekleerock** [derekleerock/Succinct#61]
https://travis-ci.org/github/derekleerock/Succinct/jobs/722252122

**Comment by derekleerock** [comment]
Looks like the problem is running jazzy - but this never failed before:

```
Could not successfully run `xcodebuild`.
Please check the build arguments.
Saved `xcodebuild` log file: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/xcodebuild-5CF207A0-755F-413F-B2CC-DE5ABEC8EBEA.log
Failed to generate documentation
/Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/lib/jazzy/executable.rb:36:in `execute_command': /Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/bin/sourcekitten ["doc", "--module-name", "Succinct", "--", "-scheme", "Succinct"] (RuntimeError)
Running xcodebuild
Could not successfully run `xcodebuild`.
Please check the build arguments.
Saved `xcodebuild` log file: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/xcodebuild-5CF207A0-755F-413F-B2CC-DE5ABEC8EBEA.log
Failed to generate documentation
	from /Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
	from /Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:78:in `block in build'
	from /Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `build'
	from /Users/travis/.rvm/gems/ruby-2.6.5/gems/jazzy-0.13.5/bin/jazzy:15:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.6.5/bin/jazzy:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.6.5/bin/jazzy:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
       13.30 real         5.31 user         3.00 sys
make: *** [documentation] Error 1
```

Current Travis build progress:
- Since it was time to do so, I updated the Travis configuration for Xcode12 which included using the Carthage wrapper.
- Succinct and SuccinctContainer tests are both running successfully on Travis w/Xcode 12.
- jazzy and dependent gems installed successfuly
- Documentation was generated successfully
- Deployment was successful

Looking at the latest successful build, it ran against Jazzy 0.13.1 with Xcode 11.3: https://travis-ci.org/github/derekleerock/Succinct/jobs/667983113

Looking at the first failed build, it ran against Jazzy 0.13.5 with Xcode 11.3: https://travis-ci.org/github/derekleerock/Succinct/jobs/722243918

Looks like this was caused by not updating the Xcode version that Travis was running against and also allowing the version of Jazzy to be updated because I did not have a gemfile to lock the version that I was using. 

TODO:
- [ ] Specify version of Jazzy in Gemfile
- [ ] Update travis configuration to use Gemfile and not install gems manually

**Comment by derekleerock** [comment]
Looking good! https://travis-ci.org/github/derekleerock/Succinct/builds/738035779
